%% Generate Figure 4 and Supplementary Figure S2
% Display phylogeny, relative amino-acid access, disease-adjusted protection
% associations, and the all-resource consumer-resource model. S2 reports
% strain call profiles, specificity, influence and predictive performance.

run(fullfile(fileparts(mfilename('fullpath')), 'prepare_figure4.m'));

scriptDir = fileparts(mfilename('fullpath'));
localRoot = fileparts(fileparts(scriptDir));
repoRoot = fileparts(localRoot);
figureDir = fullfile(repoRoot, 'results', 'figures');
tableDir = fullfile(repoRoot, 'results', 'tables', 'main');
if ~isfolder(figureDir); mkdir(figureDir); end
if ~isfolder(tableDir); mkdir(tableDir); end
set(0, 'DefaultFigureVisible', 'off');

% Compute pairwise relative-access quantities against the fixed VPI10463
% challenger. The total and class-specific deltas are shifted candidate
% breadths because VPI10463 is constant across the 21 comparisons.
aminoRows = substrateClass == "amino acid";
candidateAminoBreadth = sum(st1Calls(aminoRows, :), 1)';
vpiAminoBreadth = sum(vpiCalls(aminoRows));
totalDelta = nicheTree.Total_Breadth - sum(vpiCalls);
aminoDelta = candidateAminoBreadth - vpiAminoBreadth;
assert(sum(vpiCalls) == 23 && vpiAminoBreadth == 3, ...
    'VPI10463 total or amino-acid breadth changed unexpectedly.');
assert(all(totalDelta == nicheTree.ST1_Private - nicheTree.VPI_Private), ...
    'Total relative breadth advantage changed unexpectedly.');
assert(isequal(candidateAminoBreadth(nicheTree.Strain == "ST1-75"), 14) && ...
    isequal(candidateAminoBreadth(nicheTree.Strain == "ST1-6"), 11) && ...
    isequal(candidateAminoBreadth(nicheTree.Strain == "ST1-68"), 0), ...
    'Focused amino-acid breadth values changed unexpectedly.');

protection = nicheTree.Protection_Effect;
disease = nicheTree.Mono_Disease_Effect;
[rawRho, rawP] = corr(aminoDelta, protection, 'Type', 'Spearman');
[aminoRankResidual, protectionRankResidual, partialRho, partialP] = ...
    partial_rank_residuals(aminoDelta, protection, disease);
assert(abs(rawRho - 0.702371354675232) < 1e-12 && ...
    abs(rawP - 0.000385414772113683) < 1e-12 && ...
    abs(partialRho - 0.470057708101081) < 1e-12 && ...
    abs(partialP - 0.036494) < 1e-6, ...
    'Verified amino-acid association values changed unexpectedly.');

simpleModelFile = fullfile(repoRoot, 'results', 'analyses', ...
    'pm1_models', 'tables', ...
    'simple_pm1_model_comparison.csv');
specificityFile = fullfile(repoRoot, 'results', 'analyses', ...
    'pm1_models', 'tables', ...
    'amino_acid_specificity_score_comparison.csv');
leaveOneWellFile = fullfile(repoRoot, 'results', 'analyses', ...
    'pm1_models', 'tables', ...
    'amino_acid_leave_one_well_out.csv');
influenceFile = fullfile(repoRoot, 'results', 'analyses', ...
    'pm1_models', 'tables', ...
    'highlighted_scalar_influence_analysis.csv');
jointModelFile = fullfile(repoRoot, 'results', 'analyses', ...
    'pm1_models', 'tables', ...
    'amino_acid_specificity_joint_model.csv');
assert(all(isfile([string(simpleModelFile), string(specificityFile), ...
    string(leaveOneWellFile), string(influenceFile), ...
    string(jointModelFile)])), ...
    'The verified disease-adjusted PM1 model outputs are unavailable.');
simpleModels = readtable(simpleModelFile, 'TextType', 'string');
specificity = readtable(specificityFile, 'TextType', 'string');
leaveOneWell = readtable(leaveOneWellFile, 'TextType', 'string');
influence = readtable(influenceFile, 'TextType', 'string');
jointModel = readtable(jointModelFile, 'TextType', 'string');
diseaseModel = simpleModels(simpleModels.Model == "Disease only", :);
combinedModel = simpleModels( ...
    simpleModels.Model == "6. Amino-acid breadth + disease", :);
aminoSpecificity = specificity( ...
    specificity.Score == "Amino-acid breadth", :);
assert(height(aminoSpecificity) == 1 && ...
    abs(aminoSpecificity.Partial_Rank_P_Value - partialP) < 1e-12, ...
    'Figure 4E and S3B must use the same disease-adjusted p-value.');
assert(height(diseaseModel) == 1 && height(combinedModel) == 1 && ...
    height(aminoSpecificity) == 1, 'Unable to identify model-summary rows.');
modelStats = table(diseaseModel.OLS_Adjusted_R2, ...
    combinedModel.OLS_Adjusted_R2, diseaseModel.GLS_AICc, ...
    combinedModel.GLS_AICc, combinedModel.Resource_GLS_LRT_P_Value, ...
    aminoSpecificity.Adjusted_Permutation_P_Value, ...
    diseaseModel.LOSO_RMSE, combinedModel.LOSO_RMSE, ...
    diseaseModel.LOSO_Spearman_Rho, combinedModel.LOSO_Spearman_Rho, ...
    'VariableNames', {'Disease_Adjusted_R2', ...
    'Disease_Plus_Amino_Delta_Adjusted_R2', 'Disease_GLS_AICc', ...
    'Disease_Plus_Amino_Delta_GLS_AICc', 'Incremental_GLS_LRT_P_Value', ...
    'Incremental_Residual_Permutation_P_Value', 'Disease_LOSO_RMSE', ...
    'Disease_Plus_Amino_Delta_LOSO_RMSE', 'Disease_LOSO_Spearman_Rho', ...
    'Disease_Plus_Amino_Delta_LOSO_Spearman_Rho'});
assert(abs(modelStats.Disease_Plus_Amino_Delta_GLS_AICc - ...
    113.90695863863) < 1e-10 && ...
    abs(modelStats.Incremental_GLS_LRT_P_Value - ...
    0.00615998209449031) < 1e-12, ...
    'Verified disease-adjusted model results changed unexpectedly.');

[aminoMantelRho, aminoMantelP] = trait_phylogenetic_signal( ...
    treeFile, nicheTree.Strain, aminoDelta, 10000, 29);

% Add class-specific VPI breadths and relative advantages to the displayed
% class table. Subtracting a class constant leaves every correlation and
% FDR result unchanged.
classVPIBreadth = zeros(height(chemical), 1);
for i = 1:height(chemical)
    classVPIBreadth(i) = sum(vpiCalls(substrateClass == chemical.Category(i)));
end
chemical.VPI_Breadth = classVPIBreadth;
chemical.Interpretation = repmat( ...
    "Correlation of protection with candidate class breadth minus fixed VPI class breadth", ...
    height(chemical), 1);
chemical.Properties.VariableNames( ...
    {'Protection_Partial_Rank_Rho', ...
    'Protection_Partial_Rank_P_Value', ...
    'Protection_Partial_Rank_Q_Value'}) = ...
    {'Protection_Partial_Rank_Adjusted_For_Total_Breadth_Rho', ...
    'Protection_Partial_Rank_Adjusted_For_Total_Breadth_P_Value', ...
    'Protection_Partial_Rank_Adjusted_For_Total_Breadth_Q_Value'};

focused.Total_Delta = focused.ST1_Private - focused.VPI_Private;
focused.Amino_Delta = zeros(height(focused), 1);
for i = 1:height(focused)
    row = find(nicheTree.Strain == focused.Strain(i), 1);
    focused.Amino_Delta(i) = aminoDelta(row);
end

figure4Traits = nicheTree;
figure4Traits.Total_Relative_Breadth_Advantage = totalDelta;
figure4Traits.Amino_Acid_Breadth = candidateAminoBreadth;
figure4Traits.Amino_Acid_Relative_Breadth_Advantage = aminoDelta;
writetable(figure4Traits, fullfile(tableDir, ...
    'figure4_phylogeny_aligned_traits.csv'));
writetable(chemical, fullfile(tableDir, ...
    'figure4_class_associations.csv'));
writetable(focused, fullfile(tableDir, ...
    'figure4_focused_architecture.csv'));
writetable(modelStats, fullfile(tableDir, ...
    'figure4_disease_adjusted_model.csv'));
Association = ["Amino-acid delta vs protection"; ...
    "Partial-rank amino-acid delta vs protection given disease"; ...
    "Amino-acid delta phylogenetic signal"];
Rho = [rawRho; partialRho; aminoMantelRho];
P_Value = [rawP; partialP; aminoMantelP];
N_Strains = repmat(height(nicheTree), 3, 1);
writetable(table(Association, Rho, P_Value, N_Strains), ...
    fullfile(tableDir, 'figure4_association_statistics.csv'));

% Supplementary Figure S2 displays named strain calls and makes the
% specificity, distributed-well robustness, influential-strain sensitivity,
% and explanatory-versus-predictive boundary explicit.
nonAminoSpecificity = specificity( ...
    specificity.Score == "Non-amino-acid breadth", :);
assert(height(nonAminoSpecificity) == 1 && height(leaveOneWell) == 16, ...
    'The amino-acid specificity or leave-one-well table changed.');
aminoInfluence = influence(influence.Feature == "Amino acid breadth", :);
influence49 = aminoInfluence(aminoInfluence.Removed_Strain == "ST1-49", :);
influence68 = aminoInfluence(aminoInfluence.Removed_Strain == "ST1-68", :);
jointAmino = jointModel(startsWith(jointModel.Term, ...
    "Amino-acid breadth"), :);
jointNonAmino = jointModel(startsWith(jointModel.Term, ...
    "Non-amino breadth"), :);
assert(all([height(influence49), height(influence68), height(jointAmino), ...
    height(jointNonAmino)] == 1), ...
    'A required amino-acid robustness row is unavailable.');
assert(min(leaveOneWell.Spearman_Rho) > 0.675 && ...
    max(leaveOneWell.Spearman_Rho) < 0.720 && ...
    min(leaveOneWell.Partial_Rank_Rho) > 0.441 && ...
    max(leaveOneWell.Partial_Rank_Rho) < 0.511, ...
    'The leave-one-amino-acid-well robustness range changed.');
% This non-phylogenetic analysis is retained exactly, including its resamples.
% Preserve the original order so seed 38 reproduces the exact resamples.
resampleOrder=[53 62 75 68 12 49 57 11 65 6 23 27 20 69 63 67 58 2 25 19 66];
[ok,resampleRows]=ismember("ST1-"+string(resampleOrder)',nicheTree.Strain);
assert(all(ok));
aminoBootstrapCI=bootstrap_spearman(aminoDelta(resampleRows),protection(resampleRows),5000,38);
assert(max(abs(aminoBootstrapCI-[0.292174502769461 0.926497118269122]))<1e-10);

focusStrains = ["ST1-75", "ST1-6", "ST1-68"];
[matchedFocus, focusColumns] = ismember(focusStrains, nicheTree.Strain);
assert(all(matchedFocus), 'A focused PM1 strain is unavailable.');
focusedPm1 = table(pm1.Metabolites(rowOrder), ...
    substrateClass(rowOrder), vpiCalls(rowOrder), ...
    st1Calls(rowOrder, focusColumns(1)), ...
    st1Calls(rowOrder, focusColumns(2)), ...
    st1Calls(rowOrder, focusColumns(3)), ...
    'VariableNames', {'Substrate', 'Chemical_Class', 'VPI10463', ...
    'ST1_75', 'ST1_6', 'ST1_68'});
assert(isequal(sum(double(table2array(focusedPm1(:, 3:6))), 1), ...
    [23, 82, 76, 24]), 'Focused PM1 breadth changed unexpectedly.');

writetable(focusedPm1, fullfile(tableDir, ...
    'figureS2_strain_pm1_calls.csv'));
writetable(specificity, fullfile(tableDir, ...
    'figureS2_amino_nonamino_specificity.csv'));
writetable(leaveOneWell, fullfile(tableDir, ...
    'figureS2_amino_leave_one_well_out.csv'));
writetable(aminoInfluence, fullfile(tableDir, ...
    'figureS2_amino_leave_one_strain_out.csv'));
writetable(jointModel, fullfile(tableDir, ...
    'figureS2_amino_nonamino_joint_model.csv'));
Bootstrap_Resamples = 5000;
Bootstrap_Seed = 38;
CI_Lower = aminoBootstrapCI(1);
CI_Upper = aminoBootstrapCI(2);
writetable(table(rawRho, rawP, Bootstrap_Resamples, Bootstrap_Seed, ...
    CI_Lower, CI_Upper), fullfile(tableDir, ...
    'figureS2_amino_bootstrap.csv'));

treeData.Signal=phylogeneticSignal;
outputFile = fullfile(figureDir, 'figure4_phylogeny_resource_breadth.png');
make_figure(outputFile, treeData, nicheTree, ...
    st1Calls(rowOrder, :), vpiCalls(rowOrder), classOrder, ...
    classStarts, classEnds, classCounts, chemical, focused, ...
    totalDelta, aminoDelta, aminoRankResidual, protectionRankResidual, ...
    rawRho, rawP, partialRho, partialP, aminoMantelRho, aminoMantelP, ...
    modelStats);

writetable(phylogeneticSignal,fullfile(tableDir,'figure4_phylogenetic_signal.csv'));
writetable(focalDistance,fullfile(tableDir,'figure4_focal_patristic_distance.csv'));
writetable(table(treeOrder,'VariableNames',{'Strain'}),fullfile(tableDir,'figure4_tree_tip_order.csv'));
make_figureS2(fullfile(figureDir,'figureS2_pm1_detail_and_generalization_limits.png'), ...
    focusedPm1,classOrder,classStarts,classEnds,specificity,leaveOneWell, ...
    influence49,influence68,jointAmino,jointNonAmino,modelStats,aminoBootstrapCI);

function [xResidual, yResidual, rho, pValue] = ...
    partial_rank_residuals(x, y, disease)
n = numel(y);
design = [ones(n, 1), tiedrank(disease)];
residualizer = eye(n) - design * pinv(design);
xResidual = residualizer * tiedrank(x);
yResidual = residualizer * tiedrank(y);
rho = corr(xResidual, yResidual);
pValue = 2 * tcdf(-abs(rho) * sqrt((n-3)/(1-rho^2)), n-3);
end

function [rho, pValue] = trait_phylogenetic_signal( ...
    treeFile, strainOrder, trait, nPermutation, seed)
tree = phytreeread(treeFile);
leafNames = string(get(tree, 'LeafNames'));
distanceMatrix = squareform(pdist(tree, 'Nodes', 'leaves'));
isST1 = startsWith(leafNames, "ST1.");
leafNames = upper(replace(leafNames(isST1), ".", "-"));
distanceMatrix = distanceMatrix(isST1, isST1);
[leafNames, canonicalOrder] = sort(leafNames);
distanceMatrix = distanceMatrix(canonicalOrder, canonicalOrder);
[matched, rows] = ismember(leafNames, strainOrder);
assert(all(matched), 'Unable to align amino-acid delta to the tree.');
values = trait(rows);
upperTriangle = triu(true(size(distanceMatrix)), 1);
phylogeneticDistance = distanceMatrix(upperTriangle);
difference = abs(values - values');
rho = corr(phylogeneticDistance, difference(upperTriangle), ...
    'Type', 'Spearman');
rng(seed, 'twister');
nullRho = nan(nPermutation, 1);
for i = 1:nPermutation
    permuted = values(randperm(numel(values)));
    permutedDifference = abs(permuted - permuted');
    nullRho(i) = corr(phylogeneticDistance, ...
        permutedDifference(upperTriangle), 'Type', 'Spearman');
end
pValue = (1 + sum(abs(nullRho) >= abs(rho))) / (nPermutation + 1);
end

function ci = bootstrap_spearman(x, y, nBootstrap, seed)
rng(seed, 'twister');
n = numel(x);
bootstrapRho = nan(nBootstrap, 1);
for i = 1:nBootstrap
    rows = randi(n, n, 1);
    if std(x(rows)) > 0 && std(y(rows)) > 0
        bootstrapRho(i) = corr(x(rows), y(rows), 'Type', 'Spearman');
    end
end
ci = prctile(bootstrapRho(~isnan(bootstrapRho)), [2.5, 97.5]);
end

function make_figure(outputFile, treeData, nicheTree, st1Calls, ...
    vpiCalls, classOrder, classStarts, classEnds, classCounts, chemical, ...
    focused, totalDelta, aminoDelta, aminoResidual, protectionResidual, ...
    rawRho, rawP, partialRho, partialP, aminoMantelRho, aminoMantelP, ...
    modelStats)
palette = make_palette();
palette.StrainOrder = nicheTree.Strain;
ps = treeData.Signal;
fig = figure('Visible', 'off', 'Color', 'w', 'Units', 'inches', ...
    'Position', [0.2, 0.2, 7.5, 21.0]);

% Portrait layout aligns the phylogeny, phenotype tracks and PM1 matrix.

add_panel_heading(fig, [0.040, 0.977, 0.92, 0.017], 'A', ...
    'Disease and protection across the ST1 phylogeny');
alignedXLim = [0.5, 23.5];
axTree = axes(fig, 'Position', [0.205, 0.936, 0.755, 0.036]);
plot_tree_panel(axTree, treeData, alignedXLim, palette);
axDisease = axes(fig, 'Position', [0.205, 0.897, 0.755, 0.027]);
plot_score_track(axDisease, nicheTree, ...
    'Mono_Disease_Effect', 'Mono_Disease_CI_Lower', ...
    'Mono_Disease_CI_Upper', 'Disease score  (+ = worse)', ...
    [-6, 17], alignedXLim, palette, ps.Mantel_Rho(3), ...
    ps.Permutation_P_Value(3));
axProtection = axes(fig, 'Position', [0.205, 0.860, 0.755, 0.027]);
plot_score_track(axProtection, nicheTree, ...
    'Protection_Effect', 'Protection_CI_Lower', ...
    'Protection_CI_Upper', 'Protection score  (+ = better)', ...
    [-10, 24], alignedXLim, palette, ps.Mantel_Rho(2), ...
    ps.Permutation_P_Value(2));

add_panel_heading(fig, [0.040, 0.803, 0.92, 0.017], 'B', ...
    'PM1 responses across ST1 strains and VPI10463');
axLabels = axes(fig, 'Position', [0.205, 0.772, 0.755, 0.026]);
plot_strain_labels(axLabels, nicheTree.Strain, alignedXLim, palette);
axClassLegend = axes(fig, 'Position', [0.010, 0.627, 0.170, 0.126]);
plot_class_legend(axClassLegend, classOrder, classCounts, palette);
axClassStrip = axes(fig, 'Position', [0.185, 0.610, 0.012, 0.155]);
plot_class_strip(axClassStrip, classStarts, classEnds, palette);
axMatrix = axes(fig, 'Position', [0.205, 0.610, 0.755, 0.155]);
plot_call_matrix(axMatrix, st1Calls, vpiCalls, classEnds, ...
    alignedXLim, nicheTree.Strain, palette);
axTotalDelta = axes(fig, 'Position', [0.205, 0.570, 0.755, 0.031]);
plot_delta_track(axTotalDelta, totalDelta, [-22, 64], ...
    {'Total calls', 'relative to VPI'}, alignedXLim, palette, ...
    palette.Gray, ps.Mantel_Rho(1), ps.Permutation_P_Value(1));
axAminoDelta = axes(fig, 'Position', [0.205, 0.531, 0.755, 0.029]);
plot_delta_track(axAminoDelta, aminoDelta, [-4, 13], ...
    {'Amino-acid calls', 'relative to VPI'}, alignedXLim, palette, ...
    palette.Teal, aminoMantelRho, aminoMantelP);

axChemical = axes(fig, 'Position', [0.130, 0.429, 0.830, 0.070]);
plot_chemical_classes(axChemical, chemical, palette);
panel_label(axChemical, 'C');

axRaw = axes(fig, 'Position', [0.130, 0.300, 0.830, 0.098]);
plot_raw_delta_association(axRaw, nicheTree, aminoDelta, rawRho, rawP, ...
    chemical, palette);
panel_label(axRaw, 'D');

axAdjusted = axes(fig, 'Position', [0.130, 0.178, 0.830, 0.088]);
plot_adjusted_delta_association(axAdjusted, nicheTree, aminoResidual, ...
    protectionResidual, partialRho, partialP, modelStats, palette);
panel_label(axAdjusted, 'E');

axFocused = axes(fig, 'Position', [0.130, 0.096, 0.830, 0.045]);
plot_focused_calls(axFocused, focused, palette);
panel_label(axFocused, 'F');
axModel = axes(fig, 'Position', [0.130, 0.021, 0.830, 0.047]);
plot_model_outcomes(axModel, focused, palette);

exportgraphics(fig, outputFile, 'Resolution', 300);
[exportFolder, exportStem] = fileparts(outputFile);
vectorFolder=fullfile(exportFolder,'editable_vectors'); if ~isfolder(vectorFolder),mkdir(vectorFolder);end
exportgraphics(fig,fullfile(vectorFolder,[exportStem '.pdf']),'ContentType','vector');
print(fig,fullfile(vectorFolder,[exportStem '.svg']),'-dsvg');
savefig(fig,fullfile(vectorFolder,[exportStem '.fig']));
close(fig);
end

function make_figureS2(outputFile, focused, classOrder, classStarts, ...
    classEnds, specificity, leaveOneWell, influence49, influence68, ...
    jointAmino, jointNonAmino, modelStats, bootstrapCI)
fig = figure('Visible', 'off', 'Color', 'w', 'Units', 'inches', ...
    'Position', [0.2, 0.2, 12.0, 14.0]);

annotation(fig, 'textbox', [0.04, 0.945, 0.92, 0.045], ...
    'String', 'Amino-acid access robustness and limits of generalization', ...
    'EdgeColor', 'none', 'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', 'FontSize', 16.5, 'FontWeight', 'bold');

axA = axes(fig, 'Position', [0.175, 0.060, 0.405, 0.865]);
plot_named_pm1(axA, focused, classOrder, classStarts, classEnds);
panel_label_supp(axA, 'A');

axB = axes(fig, 'Position', [0.685, 0.700, 0.275, 0.195]);
plot_specificity_summary(axB, specificity, bootstrapCI);
panel_label_supp(axB, 'B');

axC = axes(fig, 'Position', [0.685, 0.385, 0.275, 0.235]);
plot_leave_one_well_out(axC, leaveOneWell);
panel_label_supp(axC, 'C');

axD = axes(fig, 'Position', [0.665, 0.075, 0.305, 0.235]);
plot_interpretive_boundaries(axD, influence49, influence68, ...
    jointAmino, jointNonAmino, modelStats);
panel_label_supp(axD, 'D');

export_vector_asset(fig, outputFile);
exportgraphics(fig, outputFile, 'Resolution', 300);
close(fig);
end

function plot_named_pm1(ax, focused, classOrder, classStarts, classEnds)
calls = double(table2array(focused(:, 3:6)));
nRows = height(focused);
classColors = [0.16, 0.56, 0.45; 0.23, 0.49, 0.72; ...
    0.88, 0.50, 0.16; 0.78, 0.30, 0.29; 0.55, 0.35, 0.70; ...
    0.36, 0.65, 0.27; 0.63, 0.38, 0.56; 0.40, 0.40, 0.40];
hold(ax, 'on');
for i = 1:numel(classOrder)
    y0 = classStarts(i) - 0.5;
    y1 = classEnds(i) + 0.5;
    patch(ax, [0.48, 4.52, 4.52, 0.48], [y0, y0, y1, y1], ...
        classColors(i, :), 'FaceAlpha', 0.035, 'EdgeColor', 'none');
    if i > 1
        yline(ax, y0, '-', 'Color', [0.72, 0.72, 0.72], ...
            'LineWidth', 0.7);
    end
    text(ax, 4.58, mean([y0, y1]), classOrder(i), ...
        'Color', classColors(i, :), 'FontName', 'Arial', ...
        'FontSize', 6.5, 'FontWeight', 'bold', ...
        'VerticalAlignment', 'middle');
end
for column = 1:4
    positive = find(calls(:, column) == 1);
    negative = find(calls(:, column) == 0);
    scatter(ax, repmat(column, numel(negative), 1), negative, 7, ...
        [0.82, 0.85, 0.86], 'filled', 'MarkerEdgeColor', 'none');
    scatter(ax, repmat(column, numel(positive), 1), positive, 32, ...
        [0.02, 0.44, 0.41], 'filled', 'MarkerEdgeColor', 'none');
end
set(ax, 'YDir', 'reverse', 'YLim', [0.5, nRows + 0.5], ...
    'YTick', 1:nRows, 'YTickLabel', focused.Substrate, ...
    'XTick', 1:4, ...
    'XTickLabel', ["VPI10463", "ST1-75", "ST1-6", "ST1-68"], ...
    'XAxisLocation', 'top', 'FontName', 'Arial', 'FontSize', 5.2, ...
    'TickDir', 'out', 'Box', 'on');
xlim(ax, [0.48, 5.20]);
title(ax, 'All 95 named substrates, grouped by chemical class', ...
    'FontName', 'Arial', 'FontSize', 11.0, 'FontWeight', 'bold');
text(ax, 0.01, -0.035, ...
    'large teal circle: positive call; small pale circle: no positive call', ...
    'Units', 'normalized', 'FontName', 'Arial', 'FontSize', 7.5, ...
    'HorizontalAlignment', 'left', 'Color', [0.25, 0.25, 0.25]);
end

function plot_specificity_summary(ax, specificity, bootstrapCI)
amino = specificity(specificity.Score == "Amino-acid breadth", :);
nonAmino = specificity(specificity.Score == "Non-amino-acid breadth", :);
assert(height(amino) == 1 && height(nonAmino) == 1, ...
    'Specificity rows are incomplete.');
hold(ax, 'on');
xline(ax, 0, ':', 'Color', [0.45, 0.45, 0.45], 'LineWidth', 0.9);
plot(ax, bootstrapCI, [4, 4], '-', 'Color', [0.06, 0.52, 0.46], ...
    'LineWidth', 2.6);
scatter(ax, amino.Spearman_Rho, 4, 75, [0.06, 0.52, 0.46], ...
    'filled', 'MarkerEdgeColor', 'k', 'LineWidth', 0.5);
scatter(ax, amino.Partial_Rank_Rho, 3, 72, [0.06, 0.52, 0.46], ...
    's', 'filled', 'MarkerEdgeColor', 'k', 'LineWidth', 0.5);
scatter(ax, nonAmino.Spearman_Rho, 2, 75, [0.62, 0.65, 0.67], ...
    'filled', 'MarkerEdgeColor', 'k', 'LineWidth', 0.5);
scatter(ax, nonAmino.Partial_Rank_Rho, 1, 72, [0.62, 0.65, 0.67], ...
    's', 'filled', 'MarkerEdgeColor', 'k', 'LineWidth', 0.5);
values = [amino.Spearman_Rho; amino.Partial_Rank_Rho; ...
    nonAmino.Spearman_Rho; nonAmino.Partial_Rank_Rho];
pValues = [amino.Spearman_P_Value; amino.Partial_Rank_P_Value; ...
    nonAmino.Spearman_P_Value; nonAmino.Partial_Rank_P_Value];
for i = 1:4
    labelY=5-i;
    if i==1,labelY=labelY+0.22;end % Keep text clear of the bootstrap interval.
    text(ax, values(i) + 0.025, labelY, ...
        sprintf('\\rho %.3f; p %.3g', values(i), pValues(i)), ...
        'Interpreter', 'tex', 'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', 'FontSize', 8.0);
end
set(ax, 'YLim', [0.45, 4.55], 'YTick', 1:4, ...
    'YTickLabel', ["Non-AA | disease", "Non-AA | raw", ...
    "Amino acid | disease", "Amino acid | raw"], ...
    'FontName', 'Arial', 'FontSize', 8.0, 'TickDir', 'out', ...
    'Box', 'off', 'XGrid', 'on', 'GridAlpha', 0.10);
xlim(ax, [-0.05, 1.05]);
xlabel(ax, 'Rank association with protection', ...
    'FontName', 'Arial', 'FontSize', 9.0, 'FontWeight', 'bold');
title(ax, 'Specificity survives disease adjustment', ...
    'FontName', 'Arial', 'FontSize', 11.0, 'FontWeight', 'bold');
text(ax, 0.02, 0.03, 'line: 95% strain-bootstrap interval', ...
    'Units', 'normalized', 'FontName', 'Arial', 'FontSize', 7.2, ...
    'Color', [0.35, 0.35, 0.35]);
end

function plot_leave_one_well_out(ax, leaveOneWell)
[~, order] = sort(leaveOneWell.Partial_Rank_Rho, 'descend');
data = leaveOneWell(order, :);
y = (1:height(data))';
hold(ax, 'on');
xline(ax, 0.702371354675232, '-', 'Color', [0.06, 0.52, 0.46], ...
    'LineWidth', 0.8);
xline(ax, 0.470057708101081, '-', 'Color', [0.83, 0.30, 0.12], ...
    'LineWidth', 0.8);
scatter(ax, data.Spearman_Rho, y, 42, [0.06, 0.52, 0.46], ...
    'filled', 'MarkerEdgeColor', 'w', 'LineWidth', 0.4);
scatter(ax, data.Partial_Rank_Rho, y, 42, [0.83, 0.30, 0.12], ...
    'filled', 'MarkerEdgeColor', 'w', 'LineWidth', 0.4);
set(ax, 'YDir', 'reverse', 'YTick', y, ...
    'YTickLabel', data.Removed_Well, 'FontName', 'Arial', ...
    'FontSize', 6.7, 'TickDir', 'out', 'Box', 'off', ...
    'XGrid', 'on', 'GridAlpha', 0.10);
xlim(ax, [0.40, 0.74]);
ylim(ax, [0.2, height(data) + 1.25]);
xlabel(ax, 'Correlation after removing one amino-acid well', ...
    'FontName', 'Arial', 'FontSize', 8.7, 'FontWeight', 'bold');
title(ax, 'No single well carries the association', ...
    'FontName', 'Arial', 'FontSize', 11.0, 'FontWeight', 'bold');
text(ax, 0.02, -0.10, ...
    'teal: raw Spearman   orange: disease-adjusted partial rank', ...
    'Units', 'normalized', 'FontName', 'Arial', 'FontSize', 7.2, ...
    'Color', [0.30, 0.30, 0.30]);
end

function plot_interpretive_boundaries(ax, influence49, influence68, ...
    jointAmino, jointNonAmino, modelStats)
hold(ax, 'on');
axis(ax, [0, 1, 0, 1]);
title(ax, 'What the association does—and does not—show', ...
    'FontName', 'Arial', 'FontSize', 11.0, 'FontWeight', 'bold', ...
    'Visible', 'on');

text(ax, 0.00, 0.88, 'EXPLANATORY FIT', 'FontName', 'Arial', ...
    'FontSize', 8.0, 'FontWeight', 'bold', 'Color', [0.06, 0.45, 0.40]);
text(ax, 0.00, 0.78, sprintf('Adjusted R^2: %.3f \\rightarrow %.3f', ...
    modelStats.Disease_Adjusted_R2, ...
    modelStats.Disease_Plus_Amino_Delta_Adjusted_R2), ...
    'Interpreter', 'tex', 'FontName', 'Arial', 'FontSize', 9.0);
text(ax, 0.00, 0.69, sprintf(['\\DeltaAICc %.2f; LRT p %.3f; ' ...
    'permutation p %.3f'], ...
    modelStats.Disease_Plus_Amino_Delta_GLS_AICc - ...
    modelStats.Disease_GLS_AICc, ...
    modelStats.Incremental_GLS_LRT_P_Value, ...
    modelStats.Incremental_Residual_Permutation_P_Value), ...
    'Interpreter', 'tex', 'FontName', 'Arial', 'FontSize', 8.6);

plot(ax, [0, 1], [0.61, 0.61], '-', 'Color', [0.84, 0.85, 0.86]);
text(ax, 0.00, 0.53, 'SPECIFICITY IN THE JOINT MODEL', ...
    'FontName', 'Arial', 'FontSize', 8.0, 'FontWeight', 'bold', ...
    'Color', [0.06, 0.45, 0.40]);
text(ax, 0.00, 0.43, sprintf(['amino-acid term: permutation p %.3f\n' ...
    'non-amino term: permutation p %.3f'], ...
    jointAmino.Permutation_P_Value, jointNonAmino.Permutation_P_Value), ...
    'FontName', 'Arial', 'FontSize', 8.8);

plot(ax, [0, 1], [0.34, 0.34], '-', 'Color', [0.84, 0.85, 0.86]);
text(ax, 0.00, 0.26, 'INFLUENCE AND PREDICTION LIMITS', ...
    'FontName', 'Arial', 'FontSize', 8.0, 'FontWeight', 'bold', ...
    'Color', [0.55, 0.24, 0.08]);
text(ax, 0.00, 0.15, sprintf(['partial \\rho without ST1-49: %.3f; ' ...
    'without ST1-68: %.3f'], influence49.Partial_Rank_Rho, ...
    influence68.Partial_Rank_Rho), 'Interpreter', 'tex', ...
    'FontName', 'Arial', 'FontSize', 8.6);
text(ax, 0.00, 0.05, sprintf(['LOSO RMSE: disease %.3f; ' ...
    'disease + amino acid %.3f (no gain)'], ...
    modelStats.Disease_LOSO_RMSE, ...
    modelStats.Disease_Plus_Amino_Delta_LOSO_RMSE), ...
    'FontName', 'Arial', 'FontSize', 8.6);
axis(ax, 'off');
end

function panel_label_supp(ax, label)
labelY = 1.08;
if string(label) == "A"
    labelY = 1.02;
end
text(ax, -0.15, labelY, label, 'Units', 'normalized', ...
    'FontName', 'Arial', 'FontSize', 15, 'FontWeight', 'bold', ...
    'VerticalAlignment', 'top', 'Color', [0.05, 0.05, 0.05], ...
    'BackgroundColor', 'w', 'Clipping', 'off');
end

function palette = make_palette()
palette.Charcoal = [0.23, 0.27, 0.30];
palette.Gray = [0.64, 0.66, 0.68];
palette.MidGray = [0.56, 0.59, 0.62];
palette.LightGray = [0.84, 0.85, 0.86];
palette.VeryLightGray = [0.945, 0.952, 0.956];
palette.Teal = [0.08, 0.55, 0.49];
palette.DarkTeal = [0.02, 0.42, 0.38];
palette.Red = [0.78, 0.22, 0.16];
palette.Green = [0.30, 0.66, 0.36];
palette.Blue = [0, 114, 178] / 255;
palette.Purple = [142, 90, 169] / 255;
palette.Orange = [213, 94, 0] / 255;
palette.Pink = [204, 121, 167] / 255;
palette.FocusNames = ["ST1-75", "ST1-6", "ST1-68"];
palette.FocusColors = [palette.Blue; palette.Purple; palette.Orange];
palette.HighlightNames = ["ST1-75", "ST1-6", "ST1-68"];
palette.HighlightColors = [palette.Blue; palette.Purple; ...
    palette.Orange];
palette.HighlightMarkers = {'o', '^', 's'};
palette.ClassColors = [0.18, 0.55, 0.48; 0.30, 0.55, 0.76; ...
    0.80, 0.55, 0.25; 0.78, 0.35, 0.35; 0.55, 0.39, 0.70; ...
    0.40, 0.68, 0.32; 0.70, 0.48, 0.66; 0.52, 0.52, 0.52];
end

function add_panel_heading(fig, position, letter, heading)
annotation(fig, 'textbox', position, ...
    'String', sprintf('%s   %s', letter, heading), ...
    'EdgeColor', 'none', 'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', 'FontSize', 13.0, 'FontWeight', 'bold');
end

function panel_label(ax, letter)
text(ax, -0.12, 1.09, letter, 'Units', 'normalized', ...
    'FontName', 'Arial', 'FontSize', 14.5, 'FontWeight', 'bold', ...
    'VerticalAlignment', 'top', 'Clipping', 'off');
end

function plot_tree_panel(ax, treeData, alignedXLim, palette)
hold(ax, 'on');
for i = 1:numel(treeData.BranchX)
    plot(ax, treeData.BranchX{i}, treeData.BranchY{i}, '-', ...
        'Color', palette.Charcoal, 'LineWidth', 1.15);
end
scatter(ax, treeData.LeafX, treeData.LeafY, 12, ...
    palette.Charcoal, 'filled');
 % No branch shortening is needed after recombination filtering.
for i = 1:numel(treeData.TipX)
    leafIndex = find(abs(treeData.LeafX - treeData.TipX(i)) < 1e-9, 1);
    if ~isempty(leafIndex)
        plot(ax, [treeData.TipX(i), treeData.TipX(i)], ...
            [treeData.LeafY(leafIndex), treeData.LabelBaselineY], ':', ...
            'Color', [0.86, 0.87, 0.88], 'LineWidth', 0.6);
    end
end
for j = 1:numel(palette.FocusNames)
    row = find(treeData.TipOrder == palette.FocusNames(j), 1);
    scatter(ax, treeData.TipX(row), treeData.LabelBaselineY, 30, ...
        palette.FocusColors(j, :), 'filled', ...
        'MarkerEdgeColor', [1, 1, 1], 'LineWidth', 0.6);
end
scaleLength = 1e-5;
scaleX = 22.65;
scaleStart = treeData.SourceYLim(2) - 1.40 * scaleLength;
plot(ax, [scaleX, scaleX], [scaleStart, scaleStart + scaleLength], '-', ...
    'Color', palette.Charcoal, 'LineWidth', 1.8);
text(ax, scaleX + 0.18, scaleStart + scaleLength / 2, ...
    {'10^{-5}', 'subs/site'}, 'Interpreter', 'tex', ...
    'FontName', 'Arial', 'FontSize', 8.0, ...
    'VerticalAlignment', 'middle', 'Color', palette.Charcoal);
% Rooting and support-collapse conventions are defined in the caption.
xlim(ax, alignedXLim);
ylim(ax, treeData.SourceYLim);
set(ax, 'YDir', treeData.SourceYDir, 'XTick', [], 'YTick', [], ...
    'Box', 'off', 'Color', 'none');
end

function plot_score_track(ax, nicheTree, estimateName, lowerName, ...
    upperName, yLabelText, yLimits, alignedXLim, palette, rho, pValue)
hold(ax, 'on');
x = (1:height(nicheTree))';
estimate = nicheTree.(estimateName);
lower = nicheTree.(lowerName);
upper = nicheTree.(upperName);
yline(ax, 0, ':', 'Color', [0.42, 0.42, 0.42], 'LineWidth', 0.85);
barColors = repmat(palette.Gray, height(nicheTree), 1);
for j = 1:numel(palette.HighlightNames)
    row = find(nicheTree.Strain == palette.HighlightNames(j), 1);
    if ~isempty(row); barColors(row, :) = palette.HighlightColors(j, :); end
end
bars = bar(ax, x, estimate, 0.66, 'FaceColor', 'flat', ...
    'EdgeColor', 'none');
bars.CData = barColors;
for i = 1:height(nicheTree)
    plot(ax, [x(i), x(i)], [lower(i), upper(i)], '-', ...
        'Color', palette.Charcoal, 'LineWidth', 0.8);
end
text(ax, 0.995, 0.90, sprintf(['Phylogenetic signal: ' ...
    '\\rho = %.3f; p = %.3f'], rho, pValue), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', ...
    'FontName', 'Arial', 'FontSize', 7.0, 'Color', [0.34, 0.34, 0.34], ...
    'Interpreter', 'tex');
xlim(ax, alignedXLim);
ylim(ax, yLimits);
labelLines = cellstr(split(string(yLabelText), '  '));
text(ax, -0.035, 0.50, labelLines, 'Units', 'normalized', ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'middle', ...
    'FontName', 'Arial', 'FontSize', 8.4, 'FontWeight', 'bold', ...
    'Clipping', 'off');
set(ax, 'XTick', [], 'FontName', 'Arial', 'FontSize', 8.0, ...
    'Box', 'off', 'TickDir', 'out', 'YGrid', 'on', 'GridAlpha', 0.10);
end

function plot_strain_labels(ax, strainOrder, alignedXLim, palette)
hold(ax, 'on');
axis(ax, [alignedXLim, 0, 1]);
axis(ax, 'off');
for i = 1:numel(strainOrder)
    color = [0.20, 0.20, 0.20];
    weight = 'normal';
    focusIndex = find(palette.HighlightNames == strainOrder(i), 1);
    if ~isempty(focusIndex)
        color = palette.HighlightColors(focusIndex, :);
        weight = 'bold';
    end
    text(ax, i, 0.97, strainOrder(i), 'Rotation', 58, ...
        'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', ...
        'FontName', 'Arial', 'FontSize', 7.9, ...
        'FontWeight', weight, 'Color', color, 'Interpreter', 'none');
end
text(ax, 23, 0.97, 'VPI10463', 'Rotation', 58, ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', ...
    'FontName', 'Arial', 'FontSize', 7.9, 'FontWeight', 'bold', ...
    'Color', palette.Red, 'Interpreter', 'none');
plot(ax, [22, 22], [0, 1], '-', 'Color', [0.80, 0.80, 0.80], ...
    'LineWidth', 0.8);
end

function plot_class_legend(ax, classOrder, classCounts, palette)
hold(ax, 'on');
axis(ax, [0, 1, 0, 9.4]);
axis(ax, 'off');
text(ax, 0, 9.1, 'PM1 class', 'FontName', 'Arial', ...
    'FontSize', 10.0, 'FontWeight', 'bold');
for i = 1:numel(classOrder)
    y = 8.45 - (i - 1) * 0.92;
    rectangle(ax, 'Position', [0.00, y - 0.21, 0.13, 0.35], ...
        'FaceColor', palette.ClassColors(i, :), 'EdgeColor', 'none');
    text(ax, 0.17, y, sprintf('%s (%d)', classOrder(i), classCounts(i)), ...
        'FontName', 'Arial', 'FontSize', 7.9, ...
        'VerticalAlignment', 'middle', 'Interpreter', 'none');
end
scatter(ax, 0.065, 1.10, 32, palette.DarkTeal, 'filled', ...
    'MarkerEdgeColor', 'none');
text(ax, 0.17, 1.10, 'positive call', 'FontName', 'Arial', ...
    'FontSize', 7.8, 'VerticalAlignment', 'middle');
scatter(ax, 0.065, 0.42, 15, [0.85, 0.87, 0.88], 'filled', ...
    'MarkerEdgeColor', 'none');
text(ax, 0.17, 0.42, 'no positive call', 'FontName', 'Arial', ...
    'FontSize', 7.8, 'VerticalAlignment', 'middle');
end

function plot_class_strip(ax, classStarts, classEnds, palette)
classIndex = zeros(95, 1);
for i = 1:numel(classStarts)
    classIndex(classStarts(i):classEnds(i)) = i;
end
imagesc(ax, 1, 1:95, classIndex);
colormap(ax, palette.ClassColors);
clim(ax, [0.5, 8.5]);
set(ax, 'YDir', 'reverse', 'XTick', [], 'YTick', [], 'Box', 'off');
ylim(ax, [0.5, 95.5]);
end

function plot_call_matrix(ax, st1Calls, vpiCalls, classEnds, ...
    alignedXLim, strainOrder, palette)
plotMatrix = [st1Calls, nan(size(st1Calls, 1), 1), vpiCalls];
hold(ax, 'on');
[negativeRow, negativeColumn] = find(plotMatrix == 0);
scatter(ax, negativeColumn, negativeRow, 8, [0.85, 0.87, 0.88], ...
    'filled', 'MarkerEdgeColor', 'none');
[positiveRow, positiveColumn] = find(plotMatrix == 1);
scatter(ax, positiveColumn, positiveRow, 20, palette.DarkTeal, ...
    'filled', 'MarkerEdgeColor', 'none');
for i = 1:(numel(classEnds) - 1)
    yline(ax, classEnds(i) + 0.5, '-', 'Color', [0.82, 0.84, 0.85], ...
        'LineWidth', 0.85);
end
plot(ax, [22, 22], [0.5, 95.5], '-', ...
    'Color', [0.72, 0.72, 0.72], 'LineWidth', 1.1);
for j = 1:numel(palette.FocusNames)
    x = find(strainOrder == palette.FocusNames(j), 1);
    rectangle(ax, 'Position', [x - 0.5, 0.5, 1, 95], ...
        'EdgeColor', palette.FocusColors(j, :), 'LineWidth', 1.35);
end
rectangle(ax, 'Position', [22.5, 0.5, 1, 95], ...
    'EdgeColor', palette.Red, 'LineWidth', 1.35);
xlim(ax, alignedXLim);
ylim(ax, [0.5, 95.5]);
set(ax, 'YDir', 'reverse', 'XTick', [], 'YTick', [], ...
    'Box', 'on', 'LineWidth', 0.7, 'Color', [0.985, 0.988, 0.990]);
end

function plot_delta_track(ax, values, yLimits, labelText, alignedXLim, ...
    palette, defaultColor, rho, pValue)
x = [(1:numel(values))'; 23];
plotValues = [values; 0];
colors = repmat(defaultColor, numel(plotValues), 1);
for j = 1:numel(palette.HighlightNames)
    row = find(palette.HighlightNames(j) == palette.StrainOrder, 1);
    if ~isempty(row); colors(row, :) = palette.HighlightColors(j, :); end
end
colors(end, :) = palette.Red;
bars = bar(ax, x, plotValues, 0.68, 'FaceColor', 'flat', ...
    'EdgeColor', 'none');
bars.CData = colors;
hold(ax, 'on');
yline(ax, 0, '-', 'Color', palette.Charcoal, 'LineWidth', 0.75);
[matchedFocus,focusRows] = ismember(palette.FocusNames,palette.StrainOrder);
assert(all(matchedFocus) && numel(unique(focusRows))==3);
for i = 1:numel(focusRows)
    row = focusRows(i);
    offset = 0.06 * range(yLimits) * sign(plotValues(row));
    if offset == 0; offset = 0.06 * range(yLimits); end
    text(ax, x(row), plotValues(row) + offset, ...
        sprintf('%+d', plotValues(row)), 'HorizontalAlignment', 'center', ...
        'FontName', 'Arial', 'FontSize', 7.2, 'FontWeight', 'bold', ...
        'Color', colors(row, :));
end
text(ax, 0.995, 1.14, sprintf(['Phylogenetic signal: ' ...
    '\\rho = %.3f; p = %.3f'], rho, pValue), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', ...
    'FontName', 'Arial', 'FontSize', 6.8, 'Color', [0.34, 0.34, 0.34], ...
    'Interpreter', 'tex');
xlim(ax, alignedXLim);
ylim(ax, yLimits);
ylabel(ax, labelText, 'Interpreter', 'tex', 'FontName', 'Arial', ...
    'FontSize', 8.4, 'FontWeight', 'bold');
ax.YLabel.Rotation = 0;
ax.YLabel.Units = 'normalized';
ax.YLabel.Position = [-0.075, 0.5, 0];
ax.YLabel.HorizontalAlignment = 'right';
ax.YLabel.VerticalAlignment = 'middle';
set(ax, 'XTick', [], 'FontName', 'Arial', 'FontSize', 7.8, ...
    'Box', 'off', 'TickDir', 'out', 'YGrid', 'on', 'GridAlpha', 0.10);
end

function plot_chemical_classes(ax, chemical, palette)
hold(ax, 'on');
x = (1:height(chemical))';
barColors = repmat([0.68, 0.70, 0.72], height(chemical), 1);
aminoRow = find(chemical.Category == "amino acid", 1);
barColors(aminoRow, :) = palette.Teal;
bars = bar(ax, x, chemical.Spearman_Rho, 0.70, ...
    'FaceColor', 'flat', 'EdgeColor', 'none');
bars.CData = barColors;
for i = 1:height(chemical)
    if chemical.Q_Value(i) < 0.05
        text(ax, x(i), chemical.Spearman_Rho(i) + 0.055, '*', ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', ...
            'FontName', 'Arial', 'FontSize', 13, 'FontWeight', 'bold', ...
            'Color', palette.Charcoal);
    end
end
yline(ax, 0, ':', 'Color', [0.40, 0.40, 0.40], 'LineWidth', 0.85);
set(ax, 'XTick', x, 'XTickLabel', chemical.Category, ...
    'XTickLabelRotation', 32, 'FontName', 'Arial', 'FontSize', 7.3, ...
    'Box', 'off', 'TickDir', 'out', 'YGrid', 'on', 'GridAlpha', 0.10);
xlim(ax, [0.35, height(chemical) + 0.65]);
ylim(ax, [-0.35, 0.85]);
ylabel(ax, {'Spearman \rho with', 'protection'}, 'Interpreter', 'tex', ...
    'FontName', 'Arial', 'FontSize', 9.0, 'FontWeight', 'bold');
title(ax, 'Protection by PM1 substrate class', ...
    'FontName', 'Arial', 'FontSize', 11.2, 'FontWeight', 'bold');
text(ax, 0.99, 0.94, '* BH q < 0.05', 'Units', 'normalized', ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', ...
    'FontName', 'Arial', 'FontSize', 8.0, 'Color', palette.Charcoal);
end

function plot_raw_delta_association(ax, nicheTree, aminoDelta, rho, pValue, ...
    chemical, palette)
hold(ax, 'on');
for i = 1:height(nicheTree)
    plot(ax, [aminoDelta(i), aminoDelta(i)], ...
        [nicheTree.Protection_CI_Lower(i), ...
        nicheTree.Protection_CI_Upper(i)], '-', ...
        'Color', [0.84, 0.84, 0.84], 'LineWidth', 1.0);
end
coefficients = polyfit(aminoDelta, nicheTree.Protection_Effect, 1);
xLine = linspace(min(aminoDelta), max(aminoDelta), 200);
plot(ax, xLine, polyval(coefficients, xLine), '--', ...
    'Color', [0.30, 0.30, 0.30], 'LineWidth', 1.2);
xline(ax, 0, ':', 'Color', [0.55, 0.55, 0.55]);
yline(ax, 0, ':', 'Color', [0.55, 0.55, 0.55]);
scatter(ax, aminoDelta, nicheTree.Protection_Effect, 52, palette.Gray, ...
    'filled', 'MarkerEdgeColor', 'w', 'LineWidth', 0.6);
label_highlights(ax, aminoDelta, nicheTree.Protection_Effect, ...
    nicheTree.Strain, palette, false);
aminoRow = chemical.Category == "amino acid";
text(ax, 0.985, 0.96, sprintf(['Spearman \\rho = %.3f; p = %.4f; ' ...
    'BH q = %.4f'], rho, pValue, chemical.Q_Value(aminoRow)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'top', 'FontSize', 9.0, ...
    'BackgroundColor', 'w', 'Margin', 2, 'Interpreter', 'tex');
xlim(ax, [-4, 12]);
ylim(ax, [-10, 24]);
xlabel(ax, 'Relative amino-acid calls,  \DeltaB_{AA} = ST1 - VPI10463', ...
    'Interpreter', 'tex', ...
    'FontName', 'Arial', 'FontSize', 9.8, 'FontWeight', 'bold');
ylabel(ax, 'Co-infection protection score  (+ = better)', ...
    'FontName', 'Arial', 'FontSize', 9.8, 'FontWeight', 'bold');
title(ax, 'Amino-acid access and protection', ...
    'FontName', 'Arial', 'FontSize', 11.5, 'FontWeight', 'bold');
set(ax, 'FontName', 'Arial', 'FontSize', 8.8, 'Box', 'off', ...
    'TickDir', 'out', 'XGrid', 'on', 'YGrid', 'on', 'GridAlpha', 0.10);
end

function plot_adjusted_delta_association(ax, nicheTree, xResidual, ...
    yResidual, rho, pValue, modelStats, palette)
hold(ax, 'on');
coefficients = polyfit(xResidual, yResidual, 1);
xLine = linspace(min(xResidual), max(xResidual), 200);
plot(ax, xLine, polyval(coefficients, xLine), '--', ...
    'Color', [0.30, 0.30, 0.30], 'LineWidth', 1.2);
xline(ax, 0, ':', 'Color', [0.55, 0.55, 0.55]);
yline(ax, 0, ':', 'Color', [0.55, 0.55, 0.55]);
scatter(ax, xResidual, yResidual, 52, palette.Gray, 'filled', ...
    'MarkerEdgeColor', 'w', 'LineWidth', 0.6);
label_highlights(ax, xResidual, yResidual, nicheTree.Strain, ...
    palette, true);
deltaAICc = modelStats.Disease_Plus_Amino_Delta_GLS_AICc - ...
    modelStats.Disease_GLS_AICc;
text(ax, 0.015, 0.96, sprintf(['Partial rank \\rho = %.3f; p = %.3f\n' ...
    'Adjusted R^2: %.3f \\rightarrow %.3f;  \\DeltaAICc = %.2f\n' ...
    'Incremental LRT p = %.3f; permutation p = %.3f'], rho, pValue, ...
    modelStats.Disease_Adjusted_R2, ...
    modelStats.Disease_Plus_Amino_Delta_Adjusted_R2, deltaAICc, ...
    modelStats.Incremental_GLS_LRT_P_Value, ...
    modelStats.Incremental_Residual_Permutation_P_Value), ...
    'Units', 'normalized', 'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', 'FontSize', 8.7, ...
    'BackgroundColor', 'w', 'Margin', 2, 'Interpreter', 'tex');
xlabel(ax, 'Disease-adjusted rank of \DeltaB_{AA}', ...
    'Interpreter', 'tex', 'FontName', 'Arial', ...
    'FontSize', 9.8, 'FontWeight', 'bold');
ylabel(ax, 'Disease-adjusted rank of protection', ...
    'FontName', 'Arial', 'FontSize', 9.8, 'FontWeight', 'bold');
title(ax, 'Amino-acid access after accounting for disease potential', ...
    'FontName', 'Arial', 'FontSize', 11.5, 'FontWeight', 'bold');
set(ax, 'FontName', 'Arial', 'FontSize', 8.8, 'Box', 'off', ...
    'TickDir', 'out', 'XGrid', 'on', 'YGrid', 'on', 'GridAlpha', 0.10);
end

function label_highlights(ax, x, y, strains, palette, adjusted)
if adjusted
    offsets = [0.25, 0.45; -1.20, 0.50; 0.20, -0.65];
else
    offsets = [0.35, 0.85; -1.65, 0.65; 0.30, -1.25];
end
for i = 1:numel(palette.HighlightNames)
    row = find(strains == palette.HighlightNames(i), 1);
    scatter(ax, x(row), y(row), 92, palette.HighlightColors(i, :), ...
        'filled', 'Marker', palette.HighlightMarkers{i}, ...
        'MarkerEdgeColor', 'k', 'LineWidth', 0.75);
    text(ax, x(row) + offsets(i, 1), y(row) + offsets(i, 2), ...
        palette.HighlightNames(i), 'FontSize', 8.0, ...
        'FontWeight', 'bold', 'Color', palette.HighlightColors(i, :), ...
        'BackgroundColor', 'w', 'Margin', 1.0, 'Clipping', 'on');
end
end

function plot_focused_calls(ax, focused, palette)
hold(ax, 'on');
y = (1:height(focused))';
barh(ax, y, -focused.VPI_Private, 0.56, 'FaceColor', palette.Red, ...
    'EdgeColor', 'none');
barh(ax, y, focused.Shared_With_VPI, 0.56, ...
    'FaceColor', [0.55, 0.55, 0.55], 'EdgeColor', 'none');
for i = 1:height(focused)
    rectangle(ax, 'Position', [focused.Shared_With_VPI(i), ...
        y(i) - 0.28, focused.ST1_Private(i), 0.56], ...
        'FaceColor', palette.Blue, 'EdgeColor', 'none');
    text(ax, -focused.VPI_Private(i) - 0.8, y(i), ...
        string(focused.VPI_Private(i)), 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle', 'FontName', 'Arial', ...
        'FontSize', 8.0, 'Color', palette.Red, 'FontWeight', 'bold');
    text(ax, focused.Shared_With_VPI(i) / 2, y(i), ...
        string(focused.Shared_With_VPI(i)), 'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', 'FontName', 'Arial', ...
        'FontSize', 7.6, 'Color', [1, 1, 1], 'FontWeight', 'bold');
    text(ax, focused.Shared_With_VPI(i) + focused.ST1_Private(i) / 2, ...
        y(i), string(focused.ST1_Private(i)), ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', 'FontSize', 7.6, 'Color', [1, 1, 1], ...
        'FontWeight', 'bold');
    text(ax, 88, y(i), sprintf('\\DeltaB = %+d   |   \\DeltaB_{AA} = %+d', ...
        focused.Total_Delta(i), focused.Amino_Delta(i)), ...
        'Interpreter', 'tex', 'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle', 'FontName', 'Arial', ...
        'FontSize', 8.0, 'FontWeight', 'bold', 'Color', palette.Charcoal);
end
xline(ax, 0, '-', 'Color', palette.Charcoal, 'LineWidth', 0.8);
set(ax, 'YTick', y, 'YTickLabel', focused.Strain, 'YDir', 'reverse', ...
    'FontName', 'Arial', 'FontSize', 8.8, 'Box', 'off', 'TickDir', 'out');
xlim(ax, [-12, 112]);
ylim(ax, [0.25, 3.6]);
text(ax, -8.0, 0.54, 'VPI-private', 'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', 'FontName', 'Arial', ...
    'FontSize', 7.2, 'FontWeight', 'bold', 'Color', palette.Red);
text(ax, 11.0, 0.54, 'shared', 'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', 'FontName', 'Arial', ...
    'FontSize', 7.2, 'FontWeight', 'bold', 'Color', [0.40, 0.40, 0.40]);
text(ax, 55.0, 0.54, 'ST1-private', ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'FontName', 'Arial', 'FontSize', 7.2, 'FontWeight', 'bold', ...
    'Color', palette.Blue);
title(ax, 'Shared and strain-specific PM1 calls', ...
    'FontName', 'Arial', 'FontSize', 10.8, 'FontWeight', 'bold');
end

function plot_model_outcomes(ax, focused, palette)
other = max(0, 1 - (focused.Model_Coexistence_Fraction + ...
    focused.Model_ST1_Exclusion_Fraction + ...
    focused.Model_VPI_Exclusion_Fraction));
values = [focused.Model_Coexistence_Fraction, ...
    focused.Model_ST1_Exclusion_Fraction, ...
    focused.Model_VPI_Exclusion_Fraction, other];
y = (1:height(focused))';
bars = barh(ax, y, values, 0.56, 'stacked', 'EdgeColor', 'none');
bars(1).FaceColor = palette.Green;
bars(2).FaceColor = palette.Blue;
bars(3).FaceColor = palette.Red;
bars(4).FaceColor = [0.76, 0.76, 0.76];
hold(ax, 'on');
for i = 1:height(focused)
    text(ax, 1.015, y(i), sprintf('%.1f%% persistent', ...
        100 * focused.Model_ST1_Persistence_Fraction(i)), ...
        'HorizontalAlignment', 'left', 'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', 'FontSize', 8.1, 'FontWeight', 'bold');
end
set(ax, 'YTick', y, 'YTickLabel', focused.Strain, 'YDir', 'reverse', ...
    'FontName', 'Arial', 'FontSize', 8.8, 'Box', 'off', 'TickDir', 'out');
xlim(ax, [0, 1.22]);
ylim(ax, [0.4, 3.6]);
xlabel(ax, 'Fraction of environments (\lambda sensitivity grid)', ...
    'Interpreter', 'tex', 'FontName', 'Arial', ...
    'FontSize', 9.4, 'FontWeight', 'bold');
title(ax, 'Consumer-resource model outcomes', ...
    'FontName', 'Arial', 'FontSize', 10.8, 'FontWeight', 'bold');
text(ax, 0.15, 3, 'coexistence', 'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', 'FontName', 'Arial', ...
    'FontSize', 7.2, 'FontWeight', 'bold', 'Color', [1, 1, 1]);
text(ax, 0.51, 2, 'ST1 excludes VPI', ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'FontName', 'Arial', 'FontSize', 7.2, 'FontWeight', 'bold', ...
    'Color', [1, 1, 1]);
text(ax, 0.66, 3, 'priority / neither', ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'FontName', 'Arial', 'FontSize', 7.2, 'FontWeight', 'bold', ...
    'Color', [0.25, 0.25, 0.25]);
end
