%% Generate Draft 39 Figure 3 with paired PLS-DA panels
% Replaces the extracellular heat map in panel B with a descriptive PLS-DA
% biplot using the same five strains, three matched batches, strain colors,
% batch symbols, centroid markers, and descriptive ellipses as panel A.

clear;

scriptPath = mfilename('fullpath');
scriptFile = [scriptPath, '.m'];
localRoot = fileparts(fileparts(fileparts(scriptPath)));
repoRoot = fileparts(localRoot);
previewTableRoot = fullfile(repoRoot, 'results', 'tables', 'previews');
intracellularDir = fullfile(previewTableRoot, ...
    'gcms_intracellular_matched');
extracellularDir = fullfile(previewTableRoot, ...
    'gcms_biolog_concordance');
figureDir = fullfile(repoRoot, 'results', 'figures');
tableDir = fullfile(repoRoot, 'results', 'tables', 'main');
if ~isfolder(figureDir); mkdir(figureDir); end
if ~isfolder(tableDir); mkdir(tableDir); end

intraSource = package_input('intra.xlsx');
extraSource = package_input('secretome.xlsx');
intraWorkflow = fullfile(fileparts(scriptPath), ...
    'plot_intracellular_plsda_significant_background.m');
intraContrastWorkflow = fullfile(fileparts(scriptPath), ...
    'analyze_intracellular_matched_batches.m');
extraWorkflow = fullfile(fileparts(scriptPath), ...
    'analyze_extracellular_biolog_concordance.m');

scoreFile = fullfile(intracellularDir, ...
    'intracellular_descriptive_plsda_2d_scores.csv');
loadingFile = fullfile(intracellularDir, ...
    'intracellular_descriptive_plsda_2d_loadings.csv');
componentFile = fullfile(intracellularDir, ...
    'intracellular_descriptive_plsda_component_variance.csv');
screenFile = fullfile(intracellularDir, ...
    'intracellular_significantly_above_background_screen.csv');
intraFocusedFile = fullfile(intracellularDir, ...
    'st175_st168_matched_metabolite_effects.csv');
longFile = fullfile(extracellularDir, ...
    'extracellular_five_strain_long_form.csv');
globalFile = fullfile(extracellularDir, ...
    'extracellular_matched_global_strain_tests.csv');
focusedFile = fullfile(extracellularDir, ...
    'extracellular_st175_st168_matched_metabolite_tests.csv');
focusedPairFile = fullfile(extracellularDir, ...
    'extracellular_st175_st168_matched_pairs.csv');
requiredFiles = string({intraSource, extraSource, intraWorkflow, ...
    intraContrastWorkflow, extraWorkflow, scoreFile, loadingFile, ...
    componentFile, screenFile, intraFocusedFile, longFile, globalFile, ...
    focusedFile, focusedPairFile});
assert(all(isfile(requiredFiles)), ...
    'Run the matched-batch MATLAB workflows before composing Figure 3.');

scores = readtable(scoreFile, 'TextType', 'string');
loadings = readtable(loadingFile, 'TextType', 'string');
components = readtable(componentFile, 'TextType', 'string');
screen = readtable(screenFile, 'TextType', 'string');
intraFocused = readtable(intraFocusedFile, 'TextType', 'string');
long = readtable(longFile, 'TextType', 'string');
globalTests = readtable(globalFile, 'TextType', 'string');
focusedTests = readtable(focusedFile, 'TextType', 'string');
focusedPairs = readtable(focusedPairFile, 'TextType', 'string');

strainOrder = ["ST1-75", "ST1-68", "ST1-6", "VPI10463", "R20291"];
strainColors = [
    36, 104, 162;
    225, 97, 31;
    142, 90, 169;
    217, 71, 63;
    60, 157, 86] ./ 255;
batchMarkers = {'o', 's', '^'};

assert(height(scores) == 15 && numel(unique(scores.Strain)) == 5, ...
    'Expected 15 intracellular samples from five strains.');
assert(height(loadings) == 13 && sum(screen.IncludedInPlsDa) == 13, ...
    'Expected 13 intracellular features above matched background.');
assert(height(components) == 2, 'Expected two descriptive PLS components.');
assert(all(intraFocused.BenjaminiHochbergQ >= 0.05 | ...
    isnan(intraFocused.BenjaminiHochbergQ)), ...
    ['An intracellular ST1-75/ST1-68 metabolite now survives correction; ' ...
    'revisit the manuscript interpretation.']);
assert(sum(long.ContinuousFeature) == 15 * 13, ...
    'Expected 13 continuous extracellular features for 15 samples.');

continuousMetabolite = unique(long.Metabolite(logical(long.ContinuousFeature)), ...
    'stable');

%% Matched extracellular descriptive PLS-DA
% The input is the 13-metabolite matrix of batch-matched log2 residual signal
% relative to media. This mirrors the intracellular panel's standardization,
% five-column strain response, and two-component PLS regression.
sampleOrder = unique(long.Sample, 'stable');
nSample = numel(sampleOrder);
nMetabolite = numel(continuousMetabolite);
extraX = nan(nSample, nMetabolite);
extraStrain = strings(nSample, 1);
extraBatch = nan(nSample, 1);
for i = 1:nSample
    sampleRows = long.Sample == sampleOrder(i);
    extraStrain(i) = unique(long.Strain(sampleRows));
    extraBatch(i) = unique(long.Batch(sampleRows));
    for j = 1:nMetabolite
        valueRow = sampleRows & ...
            long.Metabolite == continuousMetabolite(j);
        assert(sum(valueRow) == 1, ...
            'Expected one value per extracellular sample and metabolite.');
        extraX(i, j) = long.MatchedLog2ResidualRatio(valueRow);
    end
end
assert(nSample == 15 && all(isfinite(extraX), 'all'), ...
    'Expected a complete 15-by-13 extracellular matrix.');

extraZ = (extraX - mean(extraX, 1)) ./ std(extraX, 0, 1);
extraResponse = zeros(nSample, numel(strainOrder));
for g = 1:numel(strainOrder)
    extraResponse(extraStrain == strainOrder(g), g) = 1;
end
[extraXLoading, ~, extraXScore, ~, ~, extraPercentVariance, ~, ...
    extraStats] = plsregress(extraZ, extraResponse, 2);
assert(size(extraXScore, 2) >= 2, ...
    'Two extracellular PLS components were not returned.');

extraScores = table(sampleOrder, extraStrain, extraBatch, ...
    extraXScore(:, 1), extraXScore(:, 2), 'VariableNames', ...
    {'Sample', 'Strain', 'Batch', 'PLS1Score', 'PLS2Score'});
extraLoadings = table(continuousMetabolite, extraXLoading(:, 1), ...
    extraXLoading(:, 2), extraStats.W(:, 1), extraStats.W(:, 2), ...
    'VariableNames', {'Metabolite', 'PLS1Loading', 'PLS2Loading', ...
    'PLS1Weight', 'PLS2Weight'});
extraComponents = table(["PLS1"; "PLS2"], ...
    extraPercentVariance(1, 1:2)', extraPercentVariance(2, 1:2)', ...
    'VariableNames', {'Component', 'XVarianceFraction', ...
    'YVarianceFraction'});
assert(all(round(100 .* extraComponents.XVarianceFraction, 2) == ...
    [39.88; 30.03]), ...
    'Extracellular PLS X-variance fractions changed unexpectedly.');

prolineGlobal = globalTests(globalTests.Metabolite == "Proline", :);
glutamateGlobal = globalTests(globalTests.Metabolite == "Glutamate", :);
prolineFocused = focusedTests(focusedTests.Metabolite == "Proline", :);
assert(height(prolineGlobal) == 1 && height(glutamateGlobal) == 1 && ...
    height(prolineFocused) == 1, 'Required GC-MS test rows are unavailable.');
assert(abs(prolineFocused.PairedTP - 0.00313) < 5e-5 && ...
    abs(prolineFocused.BenjaminiHochbergQAcrossNonconstantMetabolites - ...
    0.04698) < 5e-5, 'Focused proline result changed unexpectedly.');

% Copy the exact tables used by the figure into the versioned output folder.
writetable(scores, fullfile(tableDir, 'figure3_intracellular_plsda_scores.csv'));
writetable(loadings, fullfile(tableDir, ...
    'figure3_intracellular_plsda_loadings.csv'));
writetable(components, fullfile(tableDir, ...
    'figure3_intracellular_plsda_component_variance.csv'));
writetable(screen, fullfile(tableDir, ...
    'figure3_intracellular_background_screen.csv'));
writetable(intraFocused, fullfile(tableDir, ...
    'figure3_intracellular_st175_st168_matched_tests.csv'));
writetable(long, fullfile(tableDir, ...
    'figure3_extracellular_long_form.csv'));
writetable(globalTests, fullfile(tableDir, ...
    'figure3_extracellular_global_tests.csv'));
writetable(focusedTests, fullfile(tableDir, ...
    'figure3_st175_st168_matched_tests.csv'));
writetable(focusedPairs, fullfile(tableDir, ...
    'figure3_st175_st168_matched_pairs.csv'));
writetable(extraScores, fullfile(tableDir, ...
    'figure3_extracellular_plsda_scores.csv'));
writetable(extraLoadings, fullfile(tableDir, ...
    'figure3_extracellular_plsda_loadings.csv'));
writetable(extraComponents, fullfile(tableDir, ...
    'figure3_extracellular_plsda_component_variance.csv'));

%% Figure
fig = figure('Visible', 'off', 'Color', 'w', 'Units', 'inches', ...
    'Position', [0.2, 0.2, 13.5, 9.7]);
% Match Xavier's manual Illustrator presentation (2026-09-17).

axA = axes(fig, 'Position', [0.065, 0.56, 0.425, 0.40]);
plotPlsdaBiplot(axA, scores, loadings, components, strainOrder, ...
    strainColors, batchMarkers, {'Intracellular metabolite pools'}, true, 1);
panelLabel(axA, 'A');

axB = axes(fig, 'Position', [0.56, 0.56, 0.425, 0.40]);
plotPlsdaBiplot(axB, extraScores, extraLoadings, extraComponents, ...
    strainOrder, strainColors, batchMarkers, ...
    {'Extracellular metabolite remodeling'}, false, 2);
panelLabel(axB, 'B');

axC = axes(fig, 'Position', [0.065, 0.105, 0.425, 0.36]);
plotExtracellularMetabolite(axC, long, "Proline", strainOrder, ...
    strainColors, true);
title(axC, sprintf('Proline (strain effect q=%.3g)', ...
    prolineGlobal.BenjaminiHochbergQ), 'FontWeight', 'bold');
text(axC, 0.02, 0.72, sprintf(['ST1-75/ST1-68 residual ratio %.3f\n' ...
    'paired p=%.3g; q=%.3g'], ...
    prolineFocused.GeometricResidualSignalRatio_ST1_75_Over_ST1_68, ...
    prolineFocused.PairedTP, ...
    prolineFocused.BenjaminiHochbergQAcrossNonconstantMetabolites), ...
    'Units', 'normalized', 'FontName', 'Arial', 'FontSize', 8.5, ...
    'VerticalAlignment', 'bottom', 'BackgroundColor', 'w', ...
    'EdgeColor', [0.84, 0.84, 0.84], 'Margin', 3);
panelLabel(axC, 'C');

axD = axes(fig, 'Position', [0.57, 0.105, 0.415, 0.36]);
plotExtracellularMetabolite(axD, long, "Glutamate", strainOrder, ...
    strainColors, false);
title(axD, sprintf('Glutamate (strain effect q=%.3g)', ...
    glutamateGlobal.BenjaminiHochbergQ), 'FontWeight', 'bold');
panelLabel(axD, 'D');

outputFile = fullfile(figureDir, ...
    'figure3_gcms_metabolic_programs.png');
export_draft39_vector_asset(fig, outputFile);
exportgraphics(fig, outputFile, 'Resolution', 300);
close(fig);

%% Provenance and summary
Source = ["Intracellular GC-MS workbook"; ...
    "Extracellular GC-MS workbook"; ...
    "Intracellular MATLAB workflow"; ...
    "Intracellular focused-comparison MATLAB workflow"; ...
    "Extracellular MATLAB workflow"; ...
    "Draft 39 paired-PLS-DA MATLAB compositor"];
Path = string({intraSource; extraSource; intraWorkflow; ...
    intraContrastWorkflow; extraWorkflow; scriptFile});
Role = ["Matched-media intracellular pools and PLS-DA"; ...
    "Matched-media extracellular residual signals"; ...
    "Background screen, descriptive PLS-DA, scores, and loadings"; ...
    "Matched ST1-75/ST1-68 intracellular metabolite contrasts"; ...
    "Extracellular tests, long-form data, and focused contrasts"; ...
    "Final four-panel figure with extracellular PLS-DA in panel B"];
provenance = table(Source, Path, Role);
writetable(provenance, fullfile(tableDir, ...
    'figure3_gcms_source_provenance.csv'));



summaryFile = fullfile(tableDir, 'figure3_analysis_summary.txt');
fid = fopen(summaryFile, 'w');
assert(fid >= 0, 'Unable to create Figure 3 summary.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, ['Draft 39 Figure 3: extracellular PLS-DA replaces the ' ...
    'heat map in panel B\n']);
fprintf(fid, 'Intracellular PLS-DA features above matched background: %d of %d.\n', ...
    sum(screen.IncludedInPlsDa), height(screen));
fprintf(fid, 'PLS1/PLS2 X variance: %.2f%% / %.2f%%.\n', ...
    100 * components.XVarianceFraction(1), ...
    100 * components.XVarianceFraction(2));
fprintf(fid, 'Extracellular PLS1/PLS2 X variance: %.2f%% / %.2f%%.\n', ...
    100 * extraComponents.XVarianceFraction(1), ...
    100 * extraComponents.XVarianceFraction(2));
fprintf(fid, 'Extracellular continuous features: %d.\n', ...
    numel(continuousMetabolite));
fprintf(fid, 'Global strain effects: proline q=%.5f; glutamate q=%.5f.\n', ...
    prolineGlobal.BenjaminiHochbergQ, ...
    glutamateGlobal.BenjaminiHochbergQ);
fprintf(fid, ['Focused proline ST1-75/ST1-68 ratio %.4f; paired p=%.5f; ' ...
    'q=%.5f; exact sign-flip p=%.4f.\n'], ...
    prolineFocused.GeometricResidualSignalRatio_ST1_75_Over_ST1_68, ...
    prolineFocused.PairedTP, ...
    prolineFocused.BenjaminiHochbergQAcrossNonconstantMetabolites, ...
    prolineFocused.ExactTwoSidedSignFlipP);
fprintf(fid, 'Figure: %s\n', outputFile);
disp(fileread(summaryFile));

%% Local functions
function plotPlsdaBiplot(ax, scores, loadings, components, ...
        strainOrder, colors, markers, titleLines, showLegend, ...
        variancePrecision)
hold(ax, 'on');
xline(ax, 0, 'Color', [0.88, 0.88, 0.88]);
yline(ax, 0, 'Color', [0.88, 0.88, 0.88]);
scoreMatrix = [scores.PLS1Score, scores.PLS2Score];
loadingMatrix = [loadings.PLS1Loading, loadings.PLS2Loading];
scoreRadius = 0.68 * min(max(abs(scoreMatrix(:, 1))), ...
    max(abs(scoreMatrix(:, 2))));
loadingScale = scoreRadius / max(vecnorm(loadingMatrix, 2, 2));
scaledLoading = loadingMatrix .* loadingScale;
labelPosition = spreadLoadingLabels(1.08 .* scaledLoading);

% Outline the observed within-strain score spread. With only three matched
% batches per strain, these are descriptive covariance ellipses rather than
% inferential confidence regions.
for g = 1:numel(strainOrder)
    row = scores.Strain == strainOrder(g);
    drawObservedScoreEllipse(ax, scoreMatrix(row, :), colors(g, :));
end

for j = 1:height(loadings)
    quiver(ax, 0, 0, scaledLoading(j, 1), scaledLoading(j, 2), 0, ...
        'Color', [0.53, 0.57, 0.60], 'LineWidth', 0.9, ...
        'MaxHeadSize', 0.18, 'HandleVisibility', 'off');
    text(ax, labelPosition(j, 1), labelPosition(j, 2), ...
        loadings.Metabolite(j), ...
        'FontName', 'Arial', 'FontSize', 7, ...
        'Color', [0.25, 0.28, 0.30], ...
        'HorizontalAlignment', horizontalAlignment(labelPosition(j, 1)), ...
        'VerticalAlignment', 'middle');
end

legendHandle = gobjects(numel(strainOrder), 1);
for g = 1:numel(strainOrder)
    for b = 1:3
        row = scores.Strain == strainOrder(g) & scores.Batch == b;
        scatter(ax, scores.PLS1Score(row), scores.PLS2Score(row), 62, ...
            colors(g, :), markers{b}, 'filled', 'MarkerEdgeColor', 'w', ...
            'LineWidth', 0.8, 'HandleVisibility', 'off');
    end
    row = scores.Strain == strainOrder(g);
    centroid = [mean(scores.PLS1Score(row)), mean(scores.PLS2Score(row))];
    legendHandle(g) = scatter(ax, centroid(1), centroid(2), 145, ...
        colors(g, :), 'o', 'filled', ...
        'MarkerEdgeColor', [0.14, 0.14, 0.14], 'LineWidth', 1.1);
end
axis(ax, 'equal');
box(ax, 'off');
set(ax, 'FontName', 'Arial', 'FontSize', 9, 'LineWidth', 0.9);
xlabel(ax, sprintf('PLS1 score (%.*f%% X variance)', ...
    variancePrecision, 100 * components.XVarianceFraction(1)));
ylabel(ax, sprintf('PLS2 score (%.*f%% X variance)', ...
    variancePrecision, 100 * components.XVarianceFraction(2)));
title(ax, titleLines, 'FontWeight', 'bold');
if showLegend
    legend(ax, legendHandle, strainOrder, 'Location', 'southoutside', ...
        'NumColumns', 3, 'Box', 'off', 'FontSize', 7.5);
end
end


function labelPosition = spreadLoadingLabels(labelPosition)
% Separate nearby loading labels vertically while retaining arrow direction.
for side = [-1, 1]
    if side < 0
        index = find(labelPosition(:, 1) < 0);
    else
        index = find(labelPosition(:, 1) >= 0);
    end
    if numel(index) < 2
        continue
    end
    [originalY, order] = sort(labelPosition(index, 2));
    sortedIndex = index(order);
    verticalSpan = max(range(labelPosition(:, 2)), 0.1);
    minimumSeparation = 0.055 * verticalSpan;
    adjustedY = originalY;
    for k = 2:numel(adjustedY)
        adjustedY(k) = max(adjustedY(k), ...
            adjustedY(k - 1) + minimumSeparation);
    end
    adjustedY = adjustedY + mean(originalY) - mean(adjustedY);
    labelPosition(sortedIndex, 2) = adjustedY;
end
end


function drawObservedScoreEllipse(ax, scoreValues, color)
assert(size(scoreValues, 1) >= 3 && size(scoreValues, 2) == 2, ...
    'A score ellipse requires at least three two-dimensional observations.');
center = mean(scoreValues, 1);
centered = scoreValues - center;
covarianceMatrix = cov(scoreValues);
[eigenvector, eigenvalue] = eig(covarianceMatrix, 'vector');
assert(all(eigenvalue > 0), ...
    'Within-strain score covariance must be positive definite.');

mahalanobisSquared = sum((centered / covarianceMatrix) .* centered, 2);
outlineScale = 1.04 * sqrt(max(mahalanobisSquared));
theta = linspace(0, 2 * pi, 181);
unitCircle = [cos(theta); sin(theta)];
ellipse = center' + eigenvector * ...
    diag(outlineScale .* sqrt(eigenvalue)) * unitCircle;
patch(ax, ellipse(1, :), ellipse(2, :), color, ...
    'FaceAlpha', 0.055, 'EdgeColor', color, 'EdgeAlpha', 0.78, ...
    'LineWidth', 1.15, 'HandleVisibility', 'off');
end

function plotExtracellularMetabolite(ax, long, target, strainOrder, ...
        colors, connectFocused)
hold(ax, 'on');
jitter = [-0.10; 0; 0.10];
% Pale zero-to-mean fills reproduce the author's artwork, behind all data.
for g = 1:numel(strainOrder)
    rows = long.Strain == strainOrder(g) & long.Metabolite == target;
    average = mean(long.MatchedLog2ResidualRatio(rows));
    pale = 0.945 * [1,1,1] + 0.055 * colors(g,:);
    patch(ax, g+[-0.17,0.17,0.17,-0.17], [0,0,average,average], ...
        pale, 'FaceColor', pale, 'EdgeColor', 'none', ...
        'HandleVisibility', 'off');
end
if connectFocused
    for b = 1:3
        row75 = long.Strain == "ST1-75" & long.Batch == b & ...
            long.Metabolite == target;
        row68 = long.Strain == "ST1-68" & long.Batch == b & ...
            long.Metabolite == target;
        plot(ax, [1 + jitter(b), 2 + jitter(b)], ...
            [long.MatchedLog2ResidualRatio(row75), ...
            long.MatchedLog2ResidualRatio(row68)], '-', ...
            'Color', [0.72, 0.74, 0.76], 'LineWidth', 1.0, ...
            'HandleVisibility', 'off');
    end
end
for g = 1:numel(strainOrder)
    rows = find(long.Strain == strainOrder(g) & long.Metabolite == target);
    [~, order] = sort(long.Batch(rows));
    rows = rows(order);
    scatter(ax, g + jitter, long.MatchedLog2ResidualRatio(rows), 58, ...
        colors(g, :), 'filled', 'MarkerEdgeColor', 'w', ...
        'LineWidth', 0.8);
    plot(ax, [g - 0.17, g + 0.17], ...
        repmat(mean(long.MatchedLog2ResidualRatio(rows)), 1, 2), '-', ...
        'Color', colors(g, :), 'LineWidth', 2.2);
end
yline(ax, 0, '--', 'Color', [0.56, 0.56, 0.56]);
set(ax, 'XTick', 1:numel(strainOrder), 'XTickLabel', strainOrder, ...
    'XTickLabelRotation', 25, 'FontName', 'Arial', 'FontSize', 9, ...
    'Box', 'off', 'TickDir', 'out');
ylabel(ax, 'Matched log_2 residual / media');
xlim(ax, [0.55, 5.45]);
end

function panelLabel(ax, label)
text(ax, -0.12, 1.08, label, 'Units', 'normalized', ...
    'FontName', 'Arial', 'FontSize', 15, 'FontWeight', 'bold', ...
    'VerticalAlignment', 'top');
end

function alignment = horizontalAlignment(value)
if value < 0; alignment = 'right'; else; alignment = 'left'; end
end
